# 이미지 빌드(ec2-deploy폴더에서 실행)
# docker build -t ec2-deploy -f dockerfile .
FROM        python:3.6.7-slim
MAINTAINER  folivoradev@gmail.com

ENV         export LANG=C.UTF-8

RUN         apt -y update
RUN         apt -y dist-upgrade

# Nginx, uWSGI 설치
RUN         apt -y install gcc nginx supervisor
RUN         pip3 install uwsgi
RUN         pip3 install psycopg2-binary

# 파일 복사 후 패키지 설치
# 파일의 내용이 바뀌지 않으면 pip3 install.. 부분이 실행되지 않음
COPY        requiments.txt /tmp
RUN         pip3 install -r /tmp/requiments.txt
COPY        . /tmp

# docker build할 때의 PATH에 해당하는 폴더의 전체내용을 Image의 /srv/project/폴더 내부에 복사
COPY        .   /srv/project/
WORKDIR     /srv/project

# ENV         DJANGO_SETTINGS_MODULE config.settings.production

# 프로세스를 실행할 명령
WORKDIR     /srv/project/app
RUN         python3 manage.py collectstatic --noinput

# Nginx
RUN         rm -rf  /etc/nginx/sites-available/*
RUN         rm -rf  /etc/nginx/sites-enabled/*

RUN         cp -f   /srv/project/.config/app.nginx /etc/nginx/sites-available/
RUN         ln -sf  /etc/nginx/sites-available/app.nginx /etc/nginx/sites-enabled/app.nginx

CMD         uwsgi --http :8000 --chdir /srv/project/app --wsgi config.wsgi

# supervisor
RUN         cp -f   /srv/project/.config/supervisor/nginx.conf /etc/supervisor/conf.d
RUN         cp -f   /srv/project/.config/supervisor/uwsgi.conf /etc/supervisor/conf.d
