# 이미지 빌드(ec2-deploy폴더에서 실행)
FROM        folivoradev/eb-docker:base
ENV         DJANGO_SETTINGS_MODULE config.settings.production

# docker build할 때의 PATH에 해당하는 폴더의 전체내용을 Image의 /srv/project/폴더 내부에 복사
COPY        .   /srv/project/
WORKDIR     /srv/project

# ENV         DJANGO_SETTINGS_MODULE config.settings.production

# 프로세스를 실행할 명령
WORKDIR     /srv/project/app
RUN         python3 manage.py collectstatic --noinput

# Nginx
RUN         rm -rf  /etc/nginx/sites-available/* && \
            rm -rf  /etc/nginx/sites-enabled/*

RUN         cp -f   /srv/project/.config/app.nginx /etc/nginx/sites-available/
RUN         ln -sf  /etc/nginx/sites-available/app.nginx /etc/nginx/sites-enabled/app.nginx

# supervisor
RUN         cp -f   /srv/project/.config/supervisor/nginx.conf /etc/supervisor/conf.d
RUN         cp -f   /srv/project/.config/supervisor/uwsgi.conf /etc/supervisor/conf.d

# 80번 포트 개방
EXPOSE      80

CMD         supervisord -n